services:
  - type: web
    name: gymstreak
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: INVITE_CODE
        sync: false
